language: node_js

node_js:
    - "6"

git:
  depth: 3

cache:
  yarn: true
  directories:
    - node_modules

script: "gulp && yarn test-ci"
# had errors installing coveralls with yarn, to be investigated
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"